# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class CreateExportRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'result_id': 'str',
        'format': 'str'
    }

    attribute_map = {
        'result_id': 'resultId',
        'format': 'format'
    }

    def __init__(self, result_id=None, format=None, local_vars_configuration=None):  # noqa: E501
        """CreateExportRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._result_id = None
        self._format = None
        self.discriminator = None

        self.result_id = result_id
        self.format = format

    @property
    def result_id(self):
        """Gets the result_id of this CreateExportRequest.  # noqa: E501

        The result to be exported  # noqa: E501

        :return: The result_id of this CreateExportRequest.  # noqa: E501
        :rtype: str
        """
        return self._result_id

    @result_id.setter
    def result_id(self, result_id):
        """Sets the result_id of this CreateExportRequest.

        The result to be exported  # noqa: E501

        :param result_id: The result_id of this CreateExportRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and result_id is None:  # noqa: E501
            raise ValueError("Invalid value for `result_id`, must not be `None`")  # noqa: E501

        self._result_id = result_id

    @property
    def format(self):
        """Gets the format of this CreateExportRequest.  # noqa: E501

        The format to export to  # noqa: E501

        :return: The format of this CreateExportRequest.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this CreateExportRequest.

        The format to export to  # noqa: E501

        :param format: The format of this CreateExportRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and format is None:  # noqa: E501
            raise ValueError("Invalid value for `format`, must not be `None`")  # noqa: E501

        self._format = format

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateExportRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateExportRequest):
            return True

        return self.to_dict() != other.to_dict()
