# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class FanBC(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'name': 'str',
        'direction': 'str',
        'pressure': 'FanPBC',
        'pressure_rgh': 'OneOfFanBCPressureRgh',
        'gauge_pressure': 'FanPBC',
        'gauge_pressure_rgh': 'FanPBC',
        'turbulence': 'OneOfFanBCTurbulence',
        'temperature': 'OneOfFanBCTemperature',
        'passive_scalars': 'list[FixedValuePSBC]',
        'net_radiative_heat_flux': 'OneOfFanBCNetRadiativeHeatFlux',
        'radiative_intensity_ray': 'OneOfFanBCRadiativeIntensityRay',
        'relative_humidity': 'FixedValueRHBC',
        'topological_reference': 'TopologicalReference'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'direction': 'direction',
        'pressure': 'pressure',
        'pressure_rgh': 'pressureRgh',
        'gauge_pressure': 'gaugePressure',
        'gauge_pressure_rgh': 'gaugePressureRgh',
        'turbulence': 'turbulence',
        'temperature': 'temperature',
        'passive_scalars': 'passiveScalars',
        'net_radiative_heat_flux': 'netRadiativeHeatFlux',
        'radiative_intensity_ray': 'radiativeIntensityRay',
        'relative_humidity': 'relativeHumidity',
        'topological_reference': 'topologicalReference'
    }

    def __init__(self, type='FAN', name=None, direction=None, pressure=None, pressure_rgh=None, gauge_pressure=None, gauge_pressure_rgh=None, turbulence=None, temperature=None, passive_scalars=None, net_radiative_heat_flux=None, radiative_intensity_ray=None, relative_humidity=None, topological_reference=None, local_vars_configuration=None):  # noqa: E501
        """FanBC - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._name = None
        self._direction = None
        self._pressure = None
        self._pressure_rgh = None
        self._gauge_pressure = None
        self._gauge_pressure_rgh = None
        self._turbulence = None
        self._temperature = None
        self._passive_scalars = None
        self._net_radiative_heat_flux = None
        self._radiative_intensity_ray = None
        self._relative_humidity = None
        self._topological_reference = None
        self.discriminator = None

        self.type = type
        if name is not None:
            self.name = name
        if direction is not None:
            self.direction = direction
        if pressure is not None:
            self.pressure = pressure
        if pressure_rgh is not None:
            self.pressure_rgh = pressure_rgh
        if gauge_pressure is not None:
            self.gauge_pressure = gauge_pressure
        if gauge_pressure_rgh is not None:
            self.gauge_pressure_rgh = gauge_pressure_rgh
        if turbulence is not None:
            self.turbulence = turbulence
        if temperature is not None:
            self.temperature = temperature
        if passive_scalars is not None:
            self.passive_scalars = passive_scalars
        if net_radiative_heat_flux is not None:
            self.net_radiative_heat_flux = net_radiative_heat_flux
        if radiative_intensity_ray is not None:
            self.radiative_intensity_ray = radiative_intensity_ray
        if relative_humidity is not None:
            self.relative_humidity = relative_humidity
        if topological_reference is not None:
            self.topological_reference = topological_reference

    @property
    def type(self):
        """Gets the type of this FanBC.  # noqa: E501

        This boundary condition sets the <b>pressure</b> based on the pressure drop specified as a function of the volumetric flow rate. <a href='https://www.simscale.com/knowledge-base/how-do-i-model-a-fan-curve-in-simscale/#external-fan-boundary-condition' target='_blank'>Learn more</a>  Schema name: FanBC  # noqa: E501

        :return: The type of this FanBC.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FanBC.

        This boundary condition sets the <b>pressure</b> based on the pressure drop specified as a function of the volumetric flow rate. <a href='https://www.simscale.com/knowledge-base/how-do-i-model-a-fan-curve-in-simscale/#external-fan-boundary-condition' target='_blank'>Learn more</a>  Schema name: FanBC  # noqa: E501

        :param type: The type of this FanBC.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this FanBC.  # noqa: E501


        :return: The name of this FanBC.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FanBC.


        :param name: The name of this FanBC.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def direction(self):
        """Gets the direction of this FanBC.  # noqa: E501


        :return: The direction of this FanBC.  # noqa: E501
        :rtype: str
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this FanBC.


        :param direction: The direction of this FanBC.  # noqa: E501
        :type: str
        """
        allowed_values = ["IN", "OUT"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and direction not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `direction` ({0}), must be one of {1}"  # noqa: E501
                .format(direction, allowed_values)
            )

        self._direction = direction

    @property
    def pressure(self):
        """Gets the pressure of this FanBC.  # noqa: E501


        :return: The pressure of this FanBC.  # noqa: E501
        :rtype: FanPBC
        """
        return self._pressure

    @pressure.setter
    def pressure(self, pressure):
        """Sets the pressure of this FanBC.


        :param pressure: The pressure of this FanBC.  # noqa: E501
        :type: FanPBC
        """

        self._pressure = pressure

    @property
    def pressure_rgh(self):
        """Gets the pressure_rgh of this FanBC.  # noqa: E501


        :return: The pressure_rgh of this FanBC.  # noqa: E501
        :rtype: OneOfFanBCPressureRgh
        """
        return self._pressure_rgh

    @pressure_rgh.setter
    def pressure_rgh(self, pressure_rgh):
        """Sets the pressure_rgh of this FanBC.


        :param pressure_rgh: The pressure_rgh of this FanBC.  # noqa: E501
        :type: OneOfFanBCPressureRgh
        """

        self._pressure_rgh = pressure_rgh

    @property
    def gauge_pressure(self):
        """Gets the gauge_pressure of this FanBC.  # noqa: E501


        :return: The gauge_pressure of this FanBC.  # noqa: E501
        :rtype: FanPBC
        """
        return self._gauge_pressure

    @gauge_pressure.setter
    def gauge_pressure(self, gauge_pressure):
        """Sets the gauge_pressure of this FanBC.


        :param gauge_pressure: The gauge_pressure of this FanBC.  # noqa: E501
        :type: FanPBC
        """

        self._gauge_pressure = gauge_pressure

    @property
    def gauge_pressure_rgh(self):
        """Gets the gauge_pressure_rgh of this FanBC.  # noqa: E501


        :return: The gauge_pressure_rgh of this FanBC.  # noqa: E501
        :rtype: FanPBC
        """
        return self._gauge_pressure_rgh

    @gauge_pressure_rgh.setter
    def gauge_pressure_rgh(self, gauge_pressure_rgh):
        """Sets the gauge_pressure_rgh of this FanBC.


        :param gauge_pressure_rgh: The gauge_pressure_rgh of this FanBC.  # noqa: E501
        :type: FanPBC
        """

        self._gauge_pressure_rgh = gauge_pressure_rgh

    @property
    def turbulence(self):
        """Gets the turbulence of this FanBC.  # noqa: E501


        :return: The turbulence of this FanBC.  # noqa: E501
        :rtype: OneOfFanBCTurbulence
        """
        return self._turbulence

    @turbulence.setter
    def turbulence(self, turbulence):
        """Sets the turbulence of this FanBC.


        :param turbulence: The turbulence of this FanBC.  # noqa: E501
        :type: OneOfFanBCTurbulence
        """

        self._turbulence = turbulence

    @property
    def temperature(self):
        """Gets the temperature of this FanBC.  # noqa: E501


        :return: The temperature of this FanBC.  # noqa: E501
        :rtype: OneOfFanBCTemperature
        """
        return self._temperature

    @temperature.setter
    def temperature(self, temperature):
        """Sets the temperature of this FanBC.


        :param temperature: The temperature of this FanBC.  # noqa: E501
        :type: OneOfFanBCTemperature
        """

        self._temperature = temperature

    @property
    def passive_scalars(self):
        """Gets the passive_scalars of this FanBC.  # noqa: E501

        Please choose a boundary condition for passive scalar (T).  # noqa: E501

        :return: The passive_scalars of this FanBC.  # noqa: E501
        :rtype: list[FixedValuePSBC]
        """
        return self._passive_scalars

    @passive_scalars.setter
    def passive_scalars(self, passive_scalars):
        """Sets the passive_scalars of this FanBC.

        Please choose a boundary condition for passive scalar (T).  # noqa: E501

        :param passive_scalars: The passive_scalars of this FanBC.  # noqa: E501
        :type: list[FixedValuePSBC]
        """

        self._passive_scalars = passive_scalars

    @property
    def net_radiative_heat_flux(self):
        """Gets the net_radiative_heat_flux of this FanBC.  # noqa: E501


        :return: The net_radiative_heat_flux of this FanBC.  # noqa: E501
        :rtype: OneOfFanBCNetRadiativeHeatFlux
        """
        return self._net_radiative_heat_flux

    @net_radiative_heat_flux.setter
    def net_radiative_heat_flux(self, net_radiative_heat_flux):
        """Sets the net_radiative_heat_flux of this FanBC.


        :param net_radiative_heat_flux: The net_radiative_heat_flux of this FanBC.  # noqa: E501
        :type: OneOfFanBCNetRadiativeHeatFlux
        """

        self._net_radiative_heat_flux = net_radiative_heat_flux

    @property
    def radiative_intensity_ray(self):
        """Gets the radiative_intensity_ray of this FanBC.  # noqa: E501


        :return: The radiative_intensity_ray of this FanBC.  # noqa: E501
        :rtype: OneOfFanBCRadiativeIntensityRay
        """
        return self._radiative_intensity_ray

    @radiative_intensity_ray.setter
    def radiative_intensity_ray(self, radiative_intensity_ray):
        """Sets the radiative_intensity_ray of this FanBC.


        :param radiative_intensity_ray: The radiative_intensity_ray of this FanBC.  # noqa: E501
        :type: OneOfFanBCRadiativeIntensityRay
        """

        self._radiative_intensity_ray = radiative_intensity_ray

    @property
    def relative_humidity(self):
        """Gets the relative_humidity of this FanBC.  # noqa: E501


        :return: The relative_humidity of this FanBC.  # noqa: E501
        :rtype: FixedValueRHBC
        """
        return self._relative_humidity

    @relative_humidity.setter
    def relative_humidity(self, relative_humidity):
        """Sets the relative_humidity of this FanBC.


        :param relative_humidity: The relative_humidity of this FanBC.  # noqa: E501
        :type: FixedValueRHBC
        """

        self._relative_humidity = relative_humidity

    @property
    def topological_reference(self):
        """Gets the topological_reference of this FanBC.  # noqa: E501


        :return: The topological_reference of this FanBC.  # noqa: E501
        :rtype: TopologicalReference
        """
        return self._topological_reference

    @topological_reference.setter
    def topological_reference(self, topological_reference):
        """Sets the topological_reference of this FanBC.


        :param topological_reference: The topological_reference of this FanBC.  # noqa: E501
        :type: TopologicalReference
        """

        self._topological_reference = topological_reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FanBC):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FanBC):
            return True

        return self.to_dict() != other.to_dict()
