# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class FixedPotential(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'name': 'str',
        'potential': 'DimensionalElectricPotential',
        'potential_rms': 'DimensionalElectricPotential',
        'phase': 'DimensionalAngle',
        'topological_reference': 'TopologicalReference'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'potential': 'potential',
        'potential_rms': 'potentialRMS',
        'phase': 'phase',
        'topological_reference': 'topologicalReference'
    }

    def __init__(self, type='FIXED_POTENTIAL', name=None, potential=None, potential_rms=None, phase=None, topological_reference=None, local_vars_configuration=None):  # noqa: E501
        """FixedPotential - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._name = None
        self._potential = None
        self._potential_rms = None
        self._phase = None
        self._topological_reference = None
        self.discriminator = None

        self.type = type
        if name is not None:
            self.name = name
        if potential is not None:
            self.potential = potential
        if potential_rms is not None:
            self.potential_rms = potential_rms
        if phase is not None:
            self.phase = phase
        if topological_reference is not None:
            self.topological_reference = topological_reference

    @property
    def type(self):
        """Gets the type of this FixedPotential.  # noqa: E501

        Specify a constant electric potential (voltage) on a boundary or a body.  Schema name: FixedPotential  # noqa: E501

        :return: The type of this FixedPotential.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FixedPotential.

        Specify a constant electric potential (voltage) on a boundary or a body.  Schema name: FixedPotential  # noqa: E501

        :param type: The type of this FixedPotential.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this FixedPotential.  # noqa: E501


        :return: The name of this FixedPotential.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FixedPotential.


        :param name: The name of this FixedPotential.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def potential(self):
        """Gets the potential of this FixedPotential.  # noqa: E501


        :return: The potential of this FixedPotential.  # noqa: E501
        :rtype: DimensionalElectricPotential
        """
        return self._potential

    @potential.setter
    def potential(self, potential):
        """Sets the potential of this FixedPotential.


        :param potential: The potential of this FixedPotential.  # noqa: E501
        :type: DimensionalElectricPotential
        """

        self._potential = potential

    @property
    def potential_rms(self):
        """Gets the potential_rms of this FixedPotential.  # noqa: E501


        :return: The potential_rms of this FixedPotential.  # noqa: E501
        :rtype: DimensionalElectricPotential
        """
        return self._potential_rms

    @potential_rms.setter
    def potential_rms(self, potential_rms):
        """Sets the potential_rms of this FixedPotential.


        :param potential_rms: The potential_rms of this FixedPotential.  # noqa: E501
        :type: DimensionalElectricPotential
        """

        self._potential_rms = potential_rms

    @property
    def phase(self):
        """Gets the phase of this FixedPotential.  # noqa: E501


        :return: The phase of this FixedPotential.  # noqa: E501
        :rtype: DimensionalAngle
        """
        return self._phase

    @phase.setter
    def phase(self, phase):
        """Sets the phase of this FixedPotential.


        :param phase: The phase of this FixedPotential.  # noqa: E501
        :type: DimensionalAngle
        """

        self._phase = phase

    @property
    def topological_reference(self):
        """Gets the topological_reference of this FixedPotential.  # noqa: E501


        :return: The topological_reference of this FixedPotential.  # noqa: E501
        :rtype: TopologicalReference
        """
        return self._topological_reference

    @topological_reference.setter
    def topological_reference(self, topological_reference):
        """Sets the topological_reference of this FixedPotential.


        :param topological_reference: The topological_reference of this FixedPotential.  # noqa: E501
        :type: TopologicalReference
        """

        self._topological_reference = topological_reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FixedPotential):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FixedPotential):
            return True

        return self.to_dict() != other.to_dict()
