# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class IsotropicDirectionalDependency(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'youngs_modulus': 'DimensionalFunctionPressure',
        'poissons_ratio': 'OneOfIsotropicDirectionalDependencyPoissonsRatio',
        'expansion_coefficient': 'DimensionalFunctionThermalExpansionRate',
        'reference_temperature': 'DimensionalTemperature'
    }

    attribute_map = {
        'type': 'type',
        'youngs_modulus': 'youngsModulus',
        'poissons_ratio': 'poissonsRatio',
        'expansion_coefficient': 'expansionCoefficient',
        'reference_temperature': 'referenceTemperature'
    }

    def __init__(self, type='ISOTROPIC', youngs_modulus=None, poissons_ratio=None, expansion_coefficient=None, reference_temperature=None, local_vars_configuration=None):  # noqa: E501
        """IsotropicDirectionalDependency - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._youngs_modulus = None
        self._poissons_ratio = None
        self._expansion_coefficient = None
        self._reference_temperature = None
        self.discriminator = None

        self.type = type
        if youngs_modulus is not None:
            self.youngs_modulus = youngs_modulus
        if poissons_ratio is not None:
            self.poissons_ratio = poissons_ratio
        if expansion_coefficient is not None:
            self.expansion_coefficient = expansion_coefficient
        if reference_temperature is not None:
            self.reference_temperature = reference_temperature

    @property
    def type(self):
        """Gets the type of this IsotropicDirectionalDependency.  # noqa: E501

        Schema name: IsotropicDirectionalDependency  # noqa: E501

        :return: The type of this IsotropicDirectionalDependency.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this IsotropicDirectionalDependency.

        Schema name: IsotropicDirectionalDependency  # noqa: E501

        :param type: The type of this IsotropicDirectionalDependency.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def youngs_modulus(self):
        """Gets the youngs_modulus of this IsotropicDirectionalDependency.  # noqa: E501


        :return: The youngs_modulus of this IsotropicDirectionalDependency.  # noqa: E501
        :rtype: DimensionalFunctionPressure
        """
        return self._youngs_modulus

    @youngs_modulus.setter
    def youngs_modulus(self, youngs_modulus):
        """Sets the youngs_modulus of this IsotropicDirectionalDependency.


        :param youngs_modulus: The youngs_modulus of this IsotropicDirectionalDependency.  # noqa: E501
        :type: DimensionalFunctionPressure
        """

        self._youngs_modulus = youngs_modulus

    @property
    def poissons_ratio(self):
        """Gets the poissons_ratio of this IsotropicDirectionalDependency.  # noqa: E501


        :return: The poissons_ratio of this IsotropicDirectionalDependency.  # noqa: E501
        :rtype: OneOfIsotropicDirectionalDependencyPoissonsRatio
        """
        return self._poissons_ratio

    @poissons_ratio.setter
    def poissons_ratio(self, poissons_ratio):
        """Sets the poissons_ratio of this IsotropicDirectionalDependency.


        :param poissons_ratio: The poissons_ratio of this IsotropicDirectionalDependency.  # noqa: E501
        :type: OneOfIsotropicDirectionalDependencyPoissonsRatio
        """

        self._poissons_ratio = poissons_ratio

    @property
    def expansion_coefficient(self):
        """Gets the expansion_coefficient of this IsotropicDirectionalDependency.  # noqa: E501


        :return: The expansion_coefficient of this IsotropicDirectionalDependency.  # noqa: E501
        :rtype: DimensionalFunctionThermalExpansionRate
        """
        return self._expansion_coefficient

    @expansion_coefficient.setter
    def expansion_coefficient(self, expansion_coefficient):
        """Sets the expansion_coefficient of this IsotropicDirectionalDependency.


        :param expansion_coefficient: The expansion_coefficient of this IsotropicDirectionalDependency.  # noqa: E501
        :type: DimensionalFunctionThermalExpansionRate
        """

        self._expansion_coefficient = expansion_coefficient

    @property
    def reference_temperature(self):
        """Gets the reference_temperature of this IsotropicDirectionalDependency.  # noqa: E501


        :return: The reference_temperature of this IsotropicDirectionalDependency.  # noqa: E501
        :rtype: DimensionalTemperature
        """
        return self._reference_temperature

    @reference_temperature.setter
    def reference_temperature(self, reference_temperature):
        """Sets the reference_temperature of this IsotropicDirectionalDependency.


        :param reference_temperature: The reference_temperature of this IsotropicDirectionalDependency.  # noqa: E501
        :type: DimensionalTemperature
        """

        self._reference_temperature = reference_temperature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IsotropicDirectionalDependency):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IsotropicDirectionalDependency):
            return True

        return self.to_dict() != other.to_dict()
