# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class ManualMeshSizingSimmetrix(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'maximum_edge_length': 'DimensionalLength',
        'minimum_edge_length': 'DimensionalLength',
        'curvature': 'OneOfManualMeshSizingSimmetrixCurvature'
    }

    attribute_map = {
        'type': 'type',
        'maximum_edge_length': 'maximumEdgeLength',
        'minimum_edge_length': 'minimumEdgeLength',
        'curvature': 'curvature'
    }

    def __init__(self, type='MANUAL', maximum_edge_length=None, minimum_edge_length=None, curvature=None, local_vars_configuration=None):  # noqa: E501
        """ManualMeshSizingSimmetrix - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._maximum_edge_length = None
        self._minimum_edge_length = None
        self._curvature = None
        self.discriminator = None

        self.type = type
        if maximum_edge_length is not None:
            self.maximum_edge_length = maximum_edge_length
        if minimum_edge_length is not None:
            self.minimum_edge_length = minimum_edge_length
        if curvature is not None:
            self.curvature = curvature

    @property
    def type(self):
        """Gets the type of this ManualMeshSizingSimmetrix.  # noqa: E501

        Schema name: ManualMeshSizingSimmetrix  # noqa: E501

        :return: The type of this ManualMeshSizingSimmetrix.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ManualMeshSizingSimmetrix.

        Schema name: ManualMeshSizingSimmetrix  # noqa: E501

        :param type: The type of this ManualMeshSizingSimmetrix.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def maximum_edge_length(self):
        """Gets the maximum_edge_length of this ManualMeshSizingSimmetrix.  # noqa: E501


        :return: The maximum_edge_length of this ManualMeshSizingSimmetrix.  # noqa: E501
        :rtype: DimensionalLength
        """
        return self._maximum_edge_length

    @maximum_edge_length.setter
    def maximum_edge_length(self, maximum_edge_length):
        """Sets the maximum_edge_length of this ManualMeshSizingSimmetrix.


        :param maximum_edge_length: The maximum_edge_length of this ManualMeshSizingSimmetrix.  # noqa: E501
        :type: DimensionalLength
        """

        self._maximum_edge_length = maximum_edge_length

    @property
    def minimum_edge_length(self):
        """Gets the minimum_edge_length of this ManualMeshSizingSimmetrix.  # noqa: E501


        :return: The minimum_edge_length of this ManualMeshSizingSimmetrix.  # noqa: E501
        :rtype: DimensionalLength
        """
        return self._minimum_edge_length

    @minimum_edge_length.setter
    def minimum_edge_length(self, minimum_edge_length):
        """Sets the minimum_edge_length of this ManualMeshSizingSimmetrix.


        :param minimum_edge_length: The minimum_edge_length of this ManualMeshSizingSimmetrix.  # noqa: E501
        :type: DimensionalLength
        """

        self._minimum_edge_length = minimum_edge_length

    @property
    def curvature(self):
        """Gets the curvature of this ManualMeshSizingSimmetrix.  # noqa: E501


        :return: The curvature of this ManualMeshSizingSimmetrix.  # noqa: E501
        :rtype: OneOfManualMeshSizingSimmetrixCurvature
        """
        return self._curvature

    @curvature.setter
    def curvature(self, curvature):
        """Sets the curvature of this ManualMeshSizingSimmetrix.


        :param curvature: The curvature of this ManualMeshSizingSimmetrix.  # noqa: E501
        :type: OneOfManualMeshSizingSimmetrixCurvature
        """

        self._curvature = curvature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ManualMeshSizingSimmetrix):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ManualMeshSizingSimmetrix):
            return True

        return self.to_dict() != other.to_dict()
