# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class MaterialPropertyParameter(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'key': 'str',
        'name': 'str',
        'unit': 'str'
    }

    attribute_map = {
        'key': 'key',
        'name': 'name',
        'unit': 'unit'
    }

    def __init__(self, key=None, name=None, unit=None, local_vars_configuration=None):  # noqa: E501
        """MaterialPropertyParameter - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._key = None
        self._name = None
        self._unit = None
        self.discriminator = None

        self.key = key
        if name is not None:
            self.name = name
        if unit is not None:
            self.unit = unit

    @property
    def key(self):
        """Gets the key of this MaterialPropertyParameter.  # noqa: E501

        The unique identifier of the parameter, meaningful from the physics/business perspective  # noqa: E501

        :return: The key of this MaterialPropertyParameter.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this MaterialPropertyParameter.

        The unique identifier of the parameter, meaningful from the physics/business perspective  # noqa: E501

        :param key: The key of this MaterialPropertyParameter.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and key is None:  # noqa: E501
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def name(self):
        """Gets the name of this MaterialPropertyParameter.  # noqa: E501

        Optional user facing name or label key for human identification  # noqa: E501

        :return: The name of this MaterialPropertyParameter.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MaterialPropertyParameter.

        Optional user facing name or label key for human identification  # noqa: E501

        :param name: The name of this MaterialPropertyParameter.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def unit(self):
        """Gets the unit of this MaterialPropertyParameter.  # noqa: E501

        The parameter unit  # noqa: E501

        :return: The unit of this MaterialPropertyParameter.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this MaterialPropertyParameter.

        The parameter unit  # noqa: E501

        :param unit: The unit of this MaterialPropertyParameter.  # noqa: E501
        :type: str
        """

        self._unit = unit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MaterialPropertyParameter):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MaterialPropertyParameter):
            return True

        return self.to_dict() != other.to_dict()
