# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class OneOfPacefishMeshLegacyRefinements(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'name': 'str',
        'target_resolution': 'DimensionalLength',
        'geometry_primitive_uuids': 'list[str]',
        'buffer_cells_no_extrude': 'int',
        'additional_directional_cells': 'AdditionalDirectionalCells',
        'topological_reference': 'TopologicalReference'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'target_resolution': 'targetResolution',
        'geometry_primitive_uuids': 'geometryPrimitiveUuids',
        'buffer_cells_no_extrude': 'bufferCellsNoExtrude',
        'additional_directional_cells': 'additionalDirectionalCells',
        'topological_reference': 'topologicalReference'
    }

    discriminator_value_class_map = {
        'REGION_PACEFISH': 'RegionRefinementPacefish',
        'SURFACE_PACEFISH': 'SurfaceRefinementPacefish'
    }

    def __init__(self, type='SURFACE_PACEFISH', name=None, target_resolution=None, geometry_primitive_uuids=None, buffer_cells_no_extrude=None, additional_directional_cells=None, topological_reference=None, local_vars_configuration=None):  # noqa: E501
        """OneOfPacefishMeshLegacyRefinements - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._name = None
        self._target_resolution = None
        self._geometry_primitive_uuids = None
        self._buffer_cells_no_extrude = None
        self._additional_directional_cells = None
        self._topological_reference = None
        self.discriminator = 'type'

        self.type = type
        if name is not None:
            self.name = name
        if target_resolution is not None:
            self.target_resolution = target_resolution
        if geometry_primitive_uuids is not None:
            self.geometry_primitive_uuids = geometry_primitive_uuids
        if buffer_cells_no_extrude is not None:
            self.buffer_cells_no_extrude = buffer_cells_no_extrude
        if additional_directional_cells is not None:
            self.additional_directional_cells = additional_directional_cells
        if topological_reference is not None:
            self.topological_reference = topological_reference

    @property
    def type(self):
        """Gets the type of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501

        Schema name: SurfaceRefinementPacefish  # noqa: E501

        :return: The type of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this OneOfPacefishMeshLegacyRefinements.

        Schema name: SurfaceRefinementPacefish  # noqa: E501

        :param type: The type of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501


        :return: The name of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OneOfPacefishMeshLegacyRefinements.


        :param name: The name of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def target_resolution(self):
        """Gets the target_resolution of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501


        :return: The target_resolution of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :rtype: DimensionalLength
        """
        return self._target_resolution

    @target_resolution.setter
    def target_resolution(self, target_resolution):
        """Sets the target_resolution of this OneOfPacefishMeshLegacyRefinements.


        :param target_resolution: The target_resolution of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :type: DimensionalLength
        """

        self._target_resolution = target_resolution

    @property
    def geometry_primitive_uuids(self):
        """Gets the geometry_primitive_uuids of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501


        :return: The geometry_primitive_uuids of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :rtype: list[str]
        """
        return self._geometry_primitive_uuids

    @geometry_primitive_uuids.setter
    def geometry_primitive_uuids(self, geometry_primitive_uuids):
        """Sets the geometry_primitive_uuids of this OneOfPacefishMeshLegacyRefinements.


        :param geometry_primitive_uuids: The geometry_primitive_uuids of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :type: list[str]
        """

        self._geometry_primitive_uuids = geometry_primitive_uuids

    @property
    def buffer_cells_no_extrude(self):
        """Gets the buffer_cells_no_extrude of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501

        Specify the minimum number of buffer cells between regions of different refinements.  # noqa: E501

        :return: The buffer_cells_no_extrude of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :rtype: int
        """
        return self._buffer_cells_no_extrude

    @buffer_cells_no_extrude.setter
    def buffer_cells_no_extrude(self, buffer_cells_no_extrude):
        """Sets the buffer_cells_no_extrude of this OneOfPacefishMeshLegacyRefinements.

        Specify the minimum number of buffer cells between regions of different refinements.  # noqa: E501

        :param buffer_cells_no_extrude: The buffer_cells_no_extrude of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :type: int
        """
        if (self.local_vars_configuration.client_side_validation and
                buffer_cells_no_extrude is not None and buffer_cells_no_extrude < 3):  # noqa: E501
            raise ValueError("Invalid value for `buffer_cells_no_extrude`, must be a value greater than or equal to `3`")  # noqa: E501

        self._buffer_cells_no_extrude = buffer_cells_no_extrude

    @property
    def additional_directional_cells(self):
        """Gets the additional_directional_cells of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501


        :return: The additional_directional_cells of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :rtype: AdditionalDirectionalCells
        """
        return self._additional_directional_cells

    @additional_directional_cells.setter
    def additional_directional_cells(self, additional_directional_cells):
        """Sets the additional_directional_cells of this OneOfPacefishMeshLegacyRefinements.


        :param additional_directional_cells: The additional_directional_cells of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :type: AdditionalDirectionalCells
        """

        self._additional_directional_cells = additional_directional_cells

    @property
    def topological_reference(self):
        """Gets the topological_reference of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501


        :return: The topological_reference of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :rtype: TopologicalReference
        """
        return self._topological_reference

    @topological_reference.setter
    def topological_reference(self, topological_reference):
        """Sets the topological_reference of this OneOfPacefishMeshLegacyRefinements.


        :param topological_reference: The topological_reference of this OneOfPacefishMeshLegacyRefinements.  # noqa: E501
        :type: TopologicalReference
        """

        self._topological_reference = topological_reference

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_key = self.attribute_map[self.discriminator]
        discriminator_value = data[discriminator_key]
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OneOfPacefishMeshLegacyRefinements):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OneOfPacefishMeshLegacyRefinements):
            return True

        return self.to_dict() != other.to_dict()
