# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class PressureLossCurve(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'name': 'str',
        'pressure_loss_data': 'PressureLossData',
        'directional_dependency': 'DirectionalDependency',
        'porous_media_heat_transfer': 'OneOfPressureLossCurvePorousMediaHeatTransfer',
        'topological_reference': 'TopologicalReference',
        'geometry_primitive_uuids': 'list[str]'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'pressure_loss_data': 'pressureLossData',
        'directional_dependency': 'directionalDependency',
        'porous_media_heat_transfer': 'porousMediaHeatTransfer',
        'topological_reference': 'topologicalReference',
        'geometry_primitive_uuids': 'geometryPrimitiveUuids'
    }

    def __init__(self, type='PRESSURE_LOSS_CURVE', name=None, pressure_loss_data=None, directional_dependency=None, porous_media_heat_transfer=None, topological_reference=None, geometry_primitive_uuids=None, local_vars_configuration=None):  # noqa: E501
        """PressureLossCurve - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._name = None
        self._pressure_loss_data = None
        self._directional_dependency = None
        self._porous_media_heat_transfer = None
        self._topological_reference = None
        self._geometry_primitive_uuids = None
        self.discriminator = None

        self.type = type
        if name is not None:
            self.name = name
        if pressure_loss_data is not None:
            self.pressure_loss_data = pressure_loss_data
        if directional_dependency is not None:
            self.directional_dependency = directional_dependency
        if porous_media_heat_transfer is not None:
            self.porous_media_heat_transfer = porous_media_heat_transfer
        if topological_reference is not None:
            self.topological_reference = topological_reference
        if geometry_primitive_uuids is not None:
            self.geometry_primitive_uuids = geometry_primitive_uuids

    @property
    def type(self):
        """Gets the type of this PressureLossCurve.  # noqa: E501

        Schema name: PressureLossCurve  # noqa: E501

        :return: The type of this PressureLossCurve.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PressureLossCurve.

        Schema name: PressureLossCurve  # noqa: E501

        :param type: The type of this PressureLossCurve.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this PressureLossCurve.  # noqa: E501


        :return: The name of this PressureLossCurve.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PressureLossCurve.


        :param name: The name of this PressureLossCurve.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def pressure_loss_data(self):
        """Gets the pressure_loss_data of this PressureLossCurve.  # noqa: E501


        :return: The pressure_loss_data of this PressureLossCurve.  # noqa: E501
        :rtype: PressureLossData
        """
        return self._pressure_loss_data

    @pressure_loss_data.setter
    def pressure_loss_data(self, pressure_loss_data):
        """Sets the pressure_loss_data of this PressureLossCurve.


        :param pressure_loss_data: The pressure_loss_data of this PressureLossCurve.  # noqa: E501
        :type: PressureLossData
        """

        self._pressure_loss_data = pressure_loss_data

    @property
    def directional_dependency(self):
        """Gets the directional_dependency of this PressureLossCurve.  # noqa: E501


        :return: The directional_dependency of this PressureLossCurve.  # noqa: E501
        :rtype: DirectionalDependency
        """
        return self._directional_dependency

    @directional_dependency.setter
    def directional_dependency(self, directional_dependency):
        """Sets the directional_dependency of this PressureLossCurve.


        :param directional_dependency: The directional_dependency of this PressureLossCurve.  # noqa: E501
        :type: DirectionalDependency
        """

        self._directional_dependency = directional_dependency

    @property
    def porous_media_heat_transfer(self):
        """Gets the porous_media_heat_transfer of this PressureLossCurve.  # noqa: E501


        :return: The porous_media_heat_transfer of this PressureLossCurve.  # noqa: E501
        :rtype: OneOfPressureLossCurvePorousMediaHeatTransfer
        """
        return self._porous_media_heat_transfer

    @porous_media_heat_transfer.setter
    def porous_media_heat_transfer(self, porous_media_heat_transfer):
        """Sets the porous_media_heat_transfer of this PressureLossCurve.


        :param porous_media_heat_transfer: The porous_media_heat_transfer of this PressureLossCurve.  # noqa: E501
        :type: OneOfPressureLossCurvePorousMediaHeatTransfer
        """

        self._porous_media_heat_transfer = porous_media_heat_transfer

    @property
    def topological_reference(self):
        """Gets the topological_reference of this PressureLossCurve.  # noqa: E501


        :return: The topological_reference of this PressureLossCurve.  # noqa: E501
        :rtype: TopologicalReference
        """
        return self._topological_reference

    @topological_reference.setter
    def topological_reference(self, topological_reference):
        """Sets the topological_reference of this PressureLossCurve.


        :param topological_reference: The topological_reference of this PressureLossCurve.  # noqa: E501
        :type: TopologicalReference
        """

        self._topological_reference = topological_reference

    @property
    def geometry_primitive_uuids(self):
        """Gets the geometry_primitive_uuids of this PressureLossCurve.  # noqa: E501


        :return: The geometry_primitive_uuids of this PressureLossCurve.  # noqa: E501
        :rtype: list[str]
        """
        return self._geometry_primitive_uuids

    @geometry_primitive_uuids.setter
    def geometry_primitive_uuids(self, geometry_primitive_uuids):
        """Sets the geometry_primitive_uuids of this PressureLossCurve.


        :param geometry_primitive_uuids: The geometry_primitive_uuids of this PressureLossCurve.  # noqa: E501
        :type: list[str]
        """

        self._geometry_primitive_uuids = geometry_primitive_uuids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PressureLossCurve):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PressureLossCurve):
            return True

        return self.to_dict() != other.to_dict()
