# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class RemotePointConnectionMarc(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'name': 'str',
        'behavior': 'str',
        'geometry_primitive_uuids': 'list[str]',
        'topological_reference': 'TopologicalReference'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'behavior': 'behavior',
        'geometry_primitive_uuids': 'geometryPrimitiveUuids',
        'topological_reference': 'topologicalReference'
    }

    def __init__(self, type='REMOTE_POINT_CONNECTION', name=None, behavior=None, geometry_primitive_uuids=None, topological_reference=None, local_vars_configuration=None):  # noqa: E501
        """RemotePointConnectionMarc - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._name = None
        self._behavior = None
        self._geometry_primitive_uuids = None
        self._topological_reference = None
        self.discriminator = None

        self.type = type
        if name is not None:
            self.name = name
        if behavior is not None:
            self.behavior = behavior
        if geometry_primitive_uuids is not None:
            self.geometry_primitive_uuids = geometry_primitive_uuids
        if topological_reference is not None:
            self.topological_reference = topological_reference

    @property
    def type(self):
        """Gets the type of this RemotePointConnectionMarc.  # noqa: E501

        Schema name: RemotePointConnectionMarc  # noqa: E501

        :return: The type of this RemotePointConnectionMarc.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this RemotePointConnectionMarc.

        Schema name: RemotePointConnectionMarc  # noqa: E501

        :param type: The type of this RemotePointConnectionMarc.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this RemotePointConnectionMarc.  # noqa: E501


        :return: The name of this RemotePointConnectionMarc.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RemotePointConnectionMarc.


        :param name: The name of this RemotePointConnectionMarc.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def behavior(self):
        """Gets the behavior of this RemotePointConnectionMarc.  # noqa: E501

        <p><b>Behavior</b>: Create a connector between a remote point and a set of entities of the model. The remote point can then be used in a point load or point displacement condition to apply a point force/moment load or constraint to the model.<br><ul><li><b>Rigid (RBE2)</b>: This option creates a kinematically rigid link between the reference point and the assigned entities. It ensures the connected nodes move and rotate as a single rigid body, which is ideal for modeling stiff components like bolts or heavy mounting brackets, but it can artificially over-stiffen the assembly.<br><li><b>Deformable (RBE3)</b>: This option distributes the loads and displacements of the reference point to the connected nodes using a weighted interpolation. It allows the connected faces to deform and expand naturally without adding artificial stiffness, making it suitable for distributing mass or applying loads to flexible structures.</ul></p>  # noqa: E501

        :return: The behavior of this RemotePointConnectionMarc.  # noqa: E501
        :rtype: str
        """
        return self._behavior

    @behavior.setter
    def behavior(self, behavior):
        """Sets the behavior of this RemotePointConnectionMarc.

        <p><b>Behavior</b>: Create a connector between a remote point and a set of entities of the model. The remote point can then be used in a point load or point displacement condition to apply a point force/moment load or constraint to the model.<br><ul><li><b>Rigid (RBE2)</b>: This option creates a kinematically rigid link between the reference point and the assigned entities. It ensures the connected nodes move and rotate as a single rigid body, which is ideal for modeling stiff components like bolts or heavy mounting brackets, but it can artificially over-stiffen the assembly.<br><li><b>Deformable (RBE3)</b>: This option distributes the loads and displacements of the reference point to the connected nodes using a weighted interpolation. It allows the connected faces to deform and expand naturally without adding artificial stiffness, making it suitable for distributing mass or applying loads to flexible structures.</ul></p>  # noqa: E501

        :param behavior: The behavior of this RemotePointConnectionMarc.  # noqa: E501
        :type: str
        """
        allowed_values = ["DEFORMABLE", "UNDEFORMABLE"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and behavior not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `behavior` ({0}), must be one of {1}"  # noqa: E501
                .format(behavior, allowed_values)
            )

        self._behavior = behavior

    @property
    def geometry_primitive_uuids(self):
        """Gets the geometry_primitive_uuids of this RemotePointConnectionMarc.  # noqa: E501

        <p>Create or select the point geometry primitive which should be connected to the assigned surfaces, volumes or edges via the defined connection type.</p>  # noqa: E501

        :return: The geometry_primitive_uuids of this RemotePointConnectionMarc.  # noqa: E501
        :rtype: list[str]
        """
        return self._geometry_primitive_uuids

    @geometry_primitive_uuids.setter
    def geometry_primitive_uuids(self, geometry_primitive_uuids):
        """Sets the geometry_primitive_uuids of this RemotePointConnectionMarc.

        <p>Create or select the point geometry primitive which should be connected to the assigned surfaces, volumes or edges via the defined connection type.</p>  # noqa: E501

        :param geometry_primitive_uuids: The geometry_primitive_uuids of this RemotePointConnectionMarc.  # noqa: E501
        :type: list[str]
        """

        self._geometry_primitive_uuids = geometry_primitive_uuids

    @property
    def topological_reference(self):
        """Gets the topological_reference of this RemotePointConnectionMarc.  # noqa: E501


        :return: The topological_reference of this RemotePointConnectionMarc.  # noqa: E501
        :rtype: TopologicalReference
        """
        return self._topological_reference

    @topological_reference.setter
    def topological_reference(self, topological_reference):
        """Sets the topological_reference of this RemotePointConnectionMarc.


        :param topological_reference: The topological_reference of this RemotePointConnectionMarc.  # noqa: E501
        :type: TopologicalReference
        """

        self._topological_reference = topological_reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemotePointConnectionMarc):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RemotePointConnectionMarc):
            return True

        return self.to_dict() != other.to_dict()
