# coding: utf-8

"""
    SimScale API

    The version of the OpenAPI document: 0.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from simscale_sdk.configuration import Configuration


class SubdomainFractionValueInitialCondition(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'mass_fractions': 'list[FractionValueInitialCondition]',
        'topological_reference': 'TopologicalReference',
        'geometry_primitive_uuids': 'list[str]'
    }

    attribute_map = {
        'name': 'name',
        'mass_fractions': 'massFractions',
        'topological_reference': 'topologicalReference',
        'geometry_primitive_uuids': 'geometryPrimitiveUuids'
    }

    def __init__(self, name=None, mass_fractions=None, topological_reference=None, geometry_primitive_uuids=None, local_vars_configuration=None):  # noqa: E501
        """SubdomainFractionValueInitialCondition - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._mass_fractions = None
        self._topological_reference = None
        self._geometry_primitive_uuids = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if mass_fractions is not None:
            self.mass_fractions = mass_fractions
        if topological_reference is not None:
            self.topological_reference = topological_reference
        if geometry_primitive_uuids is not None:
            self.geometry_primitive_uuids = geometry_primitive_uuids

    @property
    def name(self):
        """Gets the name of this SubdomainFractionValueInitialCondition.  # noqa: E501


        :return: The name of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SubdomainFractionValueInitialCondition.


        :param name: The name of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def mass_fractions(self):
        """Gets the mass_fractions of this SubdomainFractionValueInitialCondition.  # noqa: E501


        :return: The mass_fractions of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :rtype: list[FractionValueInitialCondition]
        """
        return self._mass_fractions

    @mass_fractions.setter
    def mass_fractions(self, mass_fractions):
        """Sets the mass_fractions of this SubdomainFractionValueInitialCondition.


        :param mass_fractions: The mass_fractions of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :type: list[FractionValueInitialCondition]
        """

        self._mass_fractions = mass_fractions

    @property
    def topological_reference(self):
        """Gets the topological_reference of this SubdomainFractionValueInitialCondition.  # noqa: E501


        :return: The topological_reference of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :rtype: TopologicalReference
        """
        return self._topological_reference

    @topological_reference.setter
    def topological_reference(self, topological_reference):
        """Sets the topological_reference of this SubdomainFractionValueInitialCondition.


        :param topological_reference: The topological_reference of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :type: TopologicalReference
        """

        self._topological_reference = topological_reference

    @property
    def geometry_primitive_uuids(self):
        """Gets the geometry_primitive_uuids of this SubdomainFractionValueInitialCondition.  # noqa: E501


        :return: The geometry_primitive_uuids of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :rtype: list[str]
        """
        return self._geometry_primitive_uuids

    @geometry_primitive_uuids.setter
    def geometry_primitive_uuids(self, geometry_primitive_uuids):
        """Sets the geometry_primitive_uuids of this SubdomainFractionValueInitialCondition.


        :param geometry_primitive_uuids: The geometry_primitive_uuids of this SubdomainFractionValueInitialCondition.  # noqa: E501
        :type: list[str]
        """

        self._geometry_primitive_uuids = geometry_primitive_uuids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubdomainFractionValueInitialCondition):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SubdomainFractionValueInitialCondition):
            return True

        return self.to_dict() != other.to_dict()
